In [13]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv("cars_clus.csv")
print(df.size)
df.head()

2544

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0.000,21.500,1.800,140.000,101.200,67.300,172.400,2.639,13.200,28.000,2.828,0.0
1,Acura,TL,39.384,19.875,0.000,28.400,3.200,225.000,108.100,70.300,192.900,3.517,17.200,25.000,3.673,0.0
2,Acura,CL,14.114,18.225,0.000,$null$,3.200,225.000,106.900,70.600,192.000,3.470,17.200,26.000,2.647,0.0
3,Acura,RL,8.588,29.725,0.000,42.000,3.500,210.000,114.600,71.400,196.600,3.850,18.000,22.000,2.150,0.0
4,Audi,A4,20.397,22.255,0.000,23.990,1.800,150.000,102.600,68.200,178.000,2.998,16.400,27.000,3.015,0.0

In [15]:
df[['sales', 'resale', 'type', 
    'price', 'engine_s', 'horsepow', 
    'wheelbas', 'width', 'length', 
    'curb_wgt', 'fuel_cap', 'mpg', 
    'lnsales', 'partition']] = df[['sales', 'resale', 'type', 
                                   'price', 'engine_s', 'horsepow', 
                                   'wheelbas', 'width', 'length', 
                                   'curb_wgt', 'fuel_cap', 'mpg', 
                                   'lnsales', 'partition']].apply(pd.to_numeric, errors='coerce')

df = df.dropna()
df = df.reset_index(drop=True)
df['kml'] = 236.25 / df['mpg']

print('shape of data set after cleaning: ', df.size)
df.head(5)

shape of data set after cleaning:  1989

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition,kml
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0,8.437500
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0,9.450000
2,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0,10.738636
3,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0,8.750000
4,Audi,A6,18.780,23.555,0.0,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0.0,10.738636

In [16]:
feature_set = df[["engine_s", "horsepow", "wheelbas", "width", "length", "curb_wgt", "fuel_cap", "mpg", "kml"]]

In [18]:
from sklearn.preprocessing import MinMaxScaler

X = feature_set.values
scaler = MinMaxScaler()
feature_mtx = scaler.fit_transform(X)
feature_mtx

array([[0.11428571, 0.21518987, 0.18655098, ..., 0.13364055, 0.43333333,
        0.30357143],
       [0.31428571, 0.43037975, 0.3362256 , ..., 0.31797235, 0.33333333,
        0.4       ],
       [0.35714286, 0.39240506, 0.47722343, ..., 0.35483871, 0.23333333,
        0.52272727],
       ...,
       [0.11428571, 0.24050633, 0.29934924, ..., 0.28110599, 0.4       ,
        0.33333333],
       [0.14285714, 0.15189873, 0.10412148, ..., 0.15668203, 0.36666667,
        0.36538462],
       [0.14285714, 0.15189873, 0.13665944, ..., 0.19815668, 0.36666667,
        0.36538462]], shape=(117, 9))

In [19]:
from sklearn.metrics.pairwise import euclidean_distances

distances = euclidean_distances(feature_mtx, feature_mtx)

distances

array([[0.        , 0.585763  , 0.78573911, ..., 0.28685109, 0.25672507,
        0.19866125],
       [0.585763  , 0.        , 0.25892304, ..., 0.36698373, 0.66436916,
        0.62297526],
       [0.78573911, 0.25892304, 0.        , ..., 0.55085974, 0.83285848,
        0.79502645],
       ...,
       [0.28685109, 0.36698373, 0.55085974, ..., 0.        , 0.41920634,
        0.35863999],
       [0.25672507, 0.66436916, 0.83285848, ..., 0.41920634, 0.        ,
        0.15212198],
       [0.19866125, 0.62297526, 0.79502645, ..., 0.35863999, 0.15212198,
        0.        ]], shape=(117, 117))

In [23]:
from sklearn.cluster import AgglomerativeClustering

alggom = AgglomerativeClustering(6, linkage='complete')
alggom.fit(distances)

alggom.labels_

/home/s2s/Projects/machine_learning/machine_learning_practice/Practice/venv/lib/python3.14/site-packages/sklearn/cluster/_agglomerative.py:585: ClusterWarning: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  out = hierarchy.linkage(X, method=linkage, metric=affinity)

array([0, 2, 2, 4, 2, 1, 4, 2, 2, 2, 2, 2, 1, 1, 2, 4, 4, 2, 2, 2, 1, 0,
       5, 4, 4, 2, 4, 2, 4, 4, 4, 3, 3, 3, 3, 1, 2, 0, 2, 4, 2, 1, 1, 1,
       3, 2, 3, 0, 4, 4, 1, 1, 0, 0, 4, 2, 0, 4, 1, 2, 2, 1, 1, 1, 0, 4,
       4, 2, 4, 1, 4, 4, 4, 2, 1, 1, 2, 4, 2, 1, 1, 0, 4, 2, 2, 1, 4, 1,
       1, 1, 4, 4, 2, 4, 4, 2, 2, 2, 4, 4, 4, 0, 0, 0, 0, 4, 2, 0, 4, 0,
       4, 3, 0, 4, 4, 0, 0])

In [24]:
df["cluster__"] = alggom.labels_
df.head()

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition,kml,cluster__
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0,8.437500,0
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0,9.450000,2
2,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0,10.738636,2
3,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0,8.750000,4
4,Audi,A6,18.780,23.555,0.0,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0.0,10.738636,2

In [ ]:
plt.Figure(figsize=(16, 14))
for label in alggom.labels_:
    subset = df[df.cluster__ == label]
    for i in subset.index:
        plt.text(subset.horsepow[i], subset.kml[i], str(subset["model"][i]), rotation=25)
    plt.scatter(subset.horsepow, subset.kml, s= subset.price*10, c=label.astype(float), label='cluster'+str(label))

plt.legend()
plt.title('Clusters')
plt.xlabel('horsepow')
plt.ylabel('kml')

ValueError: 'c' argument has 1 elements, which is inconsistent with 'x' and 'y' with size 18.